### ISSUE TITLE
Iniciando projeto  

### ISSUE THREAD

**Issue by Brunoxw2000** [Brunoxw2000/Startdb_grupo-8#1]
Adicionar um exemplo de back-end e front-end para testar a funcionalidade das ferramentas.

**Comment by gabicastrum** [comment]
## Integração Frontend (React + TypeScript) com Backend (Spring Boot)

Este issue descreve o passo a passo para integrar um frontend React com TypeScript a um backend Spring Boot, incluindo a configuração do CORS.

**1. Criação do Projeto Backend:**

O projeto backend foi gerado usando o Spring Initializr com as seguintes configurações:

* **Linguagem:** Java
* **Build Tool:** Maven
* **Dependências:** Spring Web

![Configuração do Spring Initializr](https://github.com/user-attachments/assets/f280ebc4-c5c1-4129-8e7f-af4054f6c080)


**2. Criação do Projeto Frontend:**

O projeto frontend foi criado usando o Vite, com as seguintes etapas:

```bash
npm create vite@latest frontend -- --template react-ts
```


**3. Implementação do "Hello Controller" no Backend:**

Um controlador simples ("Hello Controller") foi criado no backend para retornar uma mensagem de teste.  O servidor Spring Boot foi iniciado com o comando:

```bash
mvn spring-boot:run
```

![Hello Controller no backend](https://github.com/user-attachments/assets/d6538590-fa2c-483b-aae8-c696f79c8b31)
![Resposta do backend](https://github.com/user-attachments/assets/8b7cb810-bbc4-4d5b-9579-8e751a44606d)


**4. Configuração da API no Frontend:**

No frontend, a comunicação com o backend foi configurada usando Axios.

![Configuração da API no Frontend](https://github.com/user-attachments/assets/7be3c27e-692e-4d17-a858-6e085ddcfdb2)
![Chamada da API no Frontend](https://github.com/user-attachments/assets/aac35d54-2d02-4463-96b3-3c84ea76b65a)



**5. Configuração do CORS no Backend:**

Para permitir a comunicação entre o frontend (porta 5173) e o backend (porta 8080), foi necessário adicionar a seguinte configuração CORS ao backend:

![Configuração do CORS](https://github.com/user-attachments/assets/5c466402-d629-4fdd-b109-8fe616d5c20f)

**6. Execução do Frontend:**

Após a configuração do CORS, o frontend foi executado com o comando:

```bash
npm run dev
```

Com o backend em execução na porta 8080 e o frontend na porta 5173, a integração foi bem-sucedida.

![Frontend em execução](https://github.com/user-attachments/assets/d7c84d9e-2b3f-487d-9ebe-5b083b459aef)

**Resultado:**

Alterações feitas no `HelloController.java` são refletidas no frontend em `http://localhost:5173/`, confirmando a comunicação bem-sucedida entre frontend e backend.
